spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5


mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  typeAliasesPackage: demo.crud.entity
  global-config:
    db-config:
      id-type: ASSIGN_ID
      insert-strategy: not_empty
      update-strategy: not_empty
      select-strategy: not_empty
    banner: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    jdbc-type-for-null: null


---
#生产环境
spring:
  config:
    activate:
      on-profile: pro


---
#开发环境
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/arch_oms?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf8&connectTimeout=3000&allowPublicKeyRetrieval=true
    username: "root"
    password: "123qsx!@#"
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



