server:
  port: 9090
  servlet:
    context-path: /
spring:
  application:
    name: arch-oms-api
  freemarker:
    check-template-location: false
    settings:
      classic_compatible: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    converters:
      preferred-json-mapper: jackson

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

  profiles:
    include: db,redis
#    include: db,redis,arch,rocketmq,feign
    active: ${profile:dev}


logging:
  config: classpath:logback-spring.xml
  level:
    org.arch.oms: warn
    com.alibaba.cloud.stream.binder.rocketmq: warn
---
spring:
  config:
    activate:
      on-profile: dev

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.31.31:58887


logging:
  config: classpath:logback-spring-dev.xml
  # feign 日志配置
  level:
    org.arch.oms: info
    com.alibaba.cloud.stream.binder.rocketmq: debug