spring:
  config:
    activate:
      on-profile: prod

  datasource:
    hikari:
      connection-test-query: SELECT 1
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://139.224.225.88:3306/arch_oms?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf8&connectTimeout=3000&allowPublicKeyRetrieval=true
      username: "root"
      password: "late856147"
      maximum-pool-size: 10
      minimum-idle: 5
    url: jdbc:mysql://139.224.225.88:3306/arch_oms?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf8&connectTimeout=3000&allowPublicKeyRetrieval=true
    username: "root"
    password: "123456"


mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  typeAliasesPackage: org.arch.oms.entity,org.arch.oms.entity
  global-config:
    db-config:
      id-type: AUTO
      insert-strategy: not_empty
      update-strategy: not_empty
      select-strategy: not_empty
    #    datacenter-id: ${nodeId:${spring.nodeId:1}}
    #    worker-id: ${nodeId:${spring.nodeId:1}}
    banner: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    jdbc-type-for-null: null
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


---

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    hikari:
      connection-test-query: SELECT 1
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://139.224.225.88:3306/arch_oms?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf8&connectTimeout=3000&allowPublicKeyRetrieval=true
      username: "root"
      password: "late856147"
      maximum-pool-size: 10
      minimum-idle: 5
    url: jdbc:mysql://139.224.225.88:3306/arch_oms?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf8&connectTimeout=3000&allowPublicKeyRetrieval=true
    username: "root"
    password: "123456"


mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  typeAliasesPackage: org.arch.oms.entity,org.arch.oms.entity
  global-config:
    db-config:
      id-type: AUTO
      insert-strategy: not_empty
      update-strategy: not_empty
      select-strategy: not_empty
    #    datacenter-id: ${nodeId:${spring.nodeId:1}}
    #    worker-id: ${nodeId:${spring.nodeId:1}}
    banner: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    jdbc-type-for-null: null
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  type-enums-package: org.arch.framework.ums.enums


